Add missing header not implicitly included by libc++
In file included from ../src/CompositorFont.cpp:5:
../src/compositor.h:75:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        std::string title;
                    ^
/usr/include/c++/v1/iosfwd:210:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^