Apply alignas to variable instead of type
../src/compositor.cpp:62:7: error: 'alignas' attribute cannot be applied to types
        char alignas(16) pushConstantBuffer[128];
             ^